openapi: 3.0.0
info:
  title: Pod Run API
  version: 1.0.0
  description: API for running a pod with specified parameters

servers:
  - url: https://api-708130507334.europe-west1.run.app

paths:
  /pod/run:
    post:
      summary: Run a pod
      description: Execute a pod with the given parameters
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                pod_id:
                  type: string
                  description: The ID of the pod to run
                query:
                  type: string
                  description: The query to be processed
                data:
                  type: object
                  description: Additional data for the request
                lang:
                  type: string
                  description: The language for the response
                access_to_sources:
                  type: boolean
                  description: Whether the pod has access to sources
              required:
                - pod_id
                - query
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                # You can define the response schema here
        '400':
          description: Bad request
        '500':
          description: Internal server error