openapi: 3.0.0
info:
  title: Renforce API
  version: 1.0.0
servers:
  - url: https://api-708130507334.europe-west1.run.app
paths:
  /orchestrator/run:
    post:
      summary: Run orchestrator
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
              required:
                - query
      responses:
        '200':
          description: Successful response
          content:
            '*/*': {}
      security:
        - bearerAuth: []
      x-codeSamples:
        - lang: python
          label: Python
          source: |
            from renforce import AIOrchestrator, Renforce

            Renforce.auth(api_token="ren13_e5577c1fd352328")

            orchestrator = AIOrchestrator.init(
                model="gemini-1.5-flash-002",
                system_prompt="You are a helpful assistant.",
                output_prompt="Provide a concise response.",
                temperature=0.3,
                max_characters=550,
                min_characters=1
            )

            result = orchestrator.run(
                query="De que trata el documento?",
            )

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer